namespace ssh.Server.Models;

public sealed class SavedSshConnection
{
    public string Id { get; init; } = string.Empty;

    public string Name { get; init; } = string.Empty;

    public string Host { get; init; } = string.Empty;

    public int Port { get; init; } = 22;

    public string Username { get; init; } = string.Empty;

    public string Password { get; init; } = string.Empty;

    public string Directory { get; init; } = "/root";

    public DateTimeOffset CreatedAt { get; init; }

    public DateTimeOffset UpdatedAt { get; init; }

    public Dictionary<string, string[]> Validate(string prefix = "")
    {
        var errors = new Dictionary<string, string[]>();

        if (string.IsNullOrWhiteSpace(Host))
        {
            errors[BuildFieldName(prefix, nameof(Host))] = ["主机地址不能为空。"];
        }

        if (string.IsNullOrWhiteSpace(Username))
        {
            errors[BuildFieldName(prefix, nameof(Username))] = ["用户名不能为空。"];
        }

        if (Port is < 1 or > 65535)
        {
            errors[BuildFieldName(prefix, nameof(Port))] = ["端口必须在 1 到 65535 之间。"];
        }

        return errors;
    }

    public SavedSshConnection Normalize()
    {
        var host = Host.Trim();
        var username = Username.Trim();
        var now = DateTimeOffset.UtcNow;
        var createdAt = CreatedAt == default ? now : CreatedAt;
        var updatedAt = UpdatedAt == default ? now : UpdatedAt;

        return new SavedSshConnection
        {
            Id = string.IsNullOrWhiteSpace(Id) ? Guid.NewGuid().ToString("N") : Id.Trim(),
            Name = BuildConnectionName(Name, host, username),
            Host = host,
            Port = Port is >= 1 and <= 65535 ? Port : 22,
            Username = username,
            Password = Password ?? string.Empty,
            Directory = NormalizeDirectory(Directory),
            CreatedAt = createdAt,
            UpdatedAt = updatedAt < createdAt ? createdAt : updatedAt
        };
    }

    private static string BuildFieldName(string prefix, string fieldName)
    {
        return string.IsNullOrWhiteSpace(prefix) ? fieldName : $"{prefix}.{fieldName}";
    }

    private static string BuildConnectionName(string? name, string host, string username)
    {
        var customName = name?.Trim() ?? string.Empty;
        var autoGeneratedName = !string.IsNullOrWhiteSpace(username) && !string.IsNullOrWhiteSpace(host)
            ? $"{username}@{host}"
            : string.Empty;

        if (!string.IsNullOrWhiteSpace(customName) &&
            !string.Equals(customName, autoGeneratedName, StringComparison.Ordinal))
        {
            return customName;
        }

        if (!string.IsNullOrWhiteSpace(host))
        {
            return host;
        }

        if (!string.IsNullOrWhiteSpace(username))
        {
            return username;
        }

        return "未命名连接";
    }

    private static string NormalizeDirectory(string? path)
    {
        var normalized = (path ?? string.Empty).Replace('\\', '/').Trim();
        if (string.IsNullOrWhiteSpace(normalized))
        {
            return "/root";
        }

        if (!normalized.StartsWith('/'))
        {
            normalized = $"/{normalized}";
        }

        while (normalized.Length > 1 && normalized.EndsWith('/'))
        {
            normalized = normalized[..^1];
        }

        return normalized;
    }
}
